-- 2022년 10월 작성 게시글 + 댓글 조회
SELECT 
    b.TITLE, 
    r.BOARD_ID, 
    r.REPLY_ID, 
    r.WRITER_ID, 
    r.CONTENTS, 
    DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS b
JOIN USED_GOODS_REPLY AS r
    ON b.BOARD_ID = r.BOARD_ID
WHERE r.CREATED_DATE >= '2022-10-01'
  AND r.CREATED_DATE <  '2022-11-01'
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;
